[project]
name = "h3loviz"
version = "0.1.0"
description = "Interactive viewport sampling of tabular H3 data with HoloViews"
readme = "README.md"
authors = [
    { name = "Kimberly Wilber", email = "kimmy@kjwilber.org" }
]
requires-python = ">=3.13"
dependencies = [
    "cartopy[plotting]>=0.25.0",
    "geoviews>=1.15.1",
    "h3>=4.5.0",
    "holoviews>=1.23.2",
    "numpy>=2.0",
    "pandas>=2.2",
    "panel>=1.9.4",
    "shapely>=2.1.2",
    "xarray>=2026.7.0",
    "xdggs>=0.6.0",
]

[project.optional-dependencies]
polars = ["polars>=1.0"]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
